"""empty message

Revision ID: 824408232341
Revises: df8e56026af6
Create Date: 2017-09-06 21:32:28.014701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824408232341'
down_revision = 'df8e56026af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grid_grid_name'), 'grid', ['grid_name'], unique=True)
    op.create_table('jar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jar_name', sa.String(length=60), nullable=True),
    sa.Column('jar_available', sa.Boolean(), nullable=True),
    sa.Column('jar_active', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['grid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_item', sa.String(length=140), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['jar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card_items')
    op.drop_table('jar')
    op.drop_index(op.f('ix_grid_grid_name'), table_name='grid')
    op.drop_table('grid')
    # ### end Alembic commands ###
