"""empty message

Revision ID: df8e56026af6
Revises: 84091d8c4882
Create Date: 2017-08-29 12:27:35.573529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8e56026af6'
down_revision = '84091d8c4882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_pool_name'), 'pool', ['pool_name'], unique=True)
    op.create_table('pool_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=140), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasks')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('curr_pstn', sa.INTEGER(), nullable=True),
    sa.Column('tasks', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pool_items')
    op.drop_index(op.f('ix_pool_pool_name'), table_name='pool')
    op.drop_table('pool')
    # ### end Alembic commands ###
